### PR TITLE
Explain that code must be valid to be converted

### PR DESCRIPTION
**Pull request by zploskey**
Explain that code needs to compile cleanly before a conversion will work.
Make links look nice.

### CODE REVIEW

**Comment by chenglou** [comment]
Wait, that's not true. Your code needs to syntactically be valid beforehand, but doesn't need to compile

**Comment by zploskey** [comment]
Good point. I changed the wording.

**Comment by zploskey** [comment]
Although the best way I know of verifying that the syntax is correct is to compile it. :smile:

**Comment by zploskey** [comment]
This change was based on feedback in the discord channel when people were trying to use the script. I think the disclaimer is useful.

**Comment by chenglou** [comment]
Actually we bake this into the code itself. Lots of people skip the readme

**Comment by zploskey** [comment]
The tool produces a good bit of output when it runs. What I heard from users was that they were missing the message about some files being skipped and then being puzzled as to what had gone wrong. In fact that was exactly what I did when I did my conversion. Having a note about it in the readme as well as the output when it runs helps with keeping to the principle of least astonishment.

Additionally, I think we would really prefer that users don't have failed syntax transformations because on subsequent runs those files will already have backups and so are presumed to be transformed already.

**Comment by chenglou** [comment]
kk. Merging! I'll make an issue to address this in the code itself.

**Pull request merged**
